# Generated by Django 4.1 on 2022-09-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimages',
            options={'verbose_name': 'Post Images', 'verbose_name_plural': 'Post Images'},
        ),
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
