# Generated by Django 4.1 on 2022-09-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_postimages_options_alter_posts_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
