# Generated by Django 4.1 on 2022-09-26 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 14, 13, 35, 279361, tzinfo=datetime.timezone.utc)),
        ),
    ]
