# Generated by Django 4.1 on 2022-09-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_postimages_options_alter_posts_description'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='saved_posts',
            field=models.ManyToManyField(related_name='saved_by', to='posts.posts'),
        ),
    ]
