# Generated by Django 4.1 on 2022-09-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_author_saved_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='followings',
            field=models.ManyToManyField(related_name='followers', to='users.author'),
        ),
    ]
