# Generated by Django 4.1 on 2022-10-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_author_followings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='followings',
        ),
        migrations.AddField(
            model_name='author',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='users.author'),
        ),
    ]
